# Generated by Django 4.1.2 on 2024-06-28 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='producto',
        ),
        migrations.RemoveField(
            model_name='order',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_ordered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='date_added',
        ),
    ]
