# Generated by Django 4.1.2 on 2024-06-28 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_name_customer_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='id_transaccion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
