# Generated by Django 4.1.2 on 2024-06-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_delete_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
