# Generated by Django 4.1.2 on 2024-07-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_product_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='donador',
            field=models.BooleanField(default=False),
        ),
    ]
