# Generated by Django 4.1.2 on 2025-06-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_customer_donador'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
